// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.1+9110c693767c1dde2665b2b57939333478b12036
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DotNet.Kafka.MultiEventTopic
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.1+9110c693767c1dde2665b2b57939333478b12036")]
	public partial class AccountUnblocked : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"AccountUnblocked\",\"namespace\":\"DotNet.Kafka.MultiEventTo" +
				"pic\",\"fields\":[{\"name\":\"eventId\",\"type\":\"string\"},{\"name\":\"accountId\",\"type\":\"st" +
				"ring\"},{\"name\":\"occurredAt\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-milli" +
				"s\"}}]}");
		private string _eventId;
		private string _accountId;
		private System.DateTime _occurredAt;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return AccountUnblocked._SCHEMA;
			}
		}
		public string eventId
		{
			get
			{
				return this._eventId;
			}
			set
			{
				this._eventId = value;
			}
		}
		public string accountId
		{
			get
			{
				return this._accountId;
			}
			set
			{
				this._accountId = value;
			}
		}
		public System.DateTime occurredAt
		{
			get
			{
				return this._occurredAt;
			}
			set
			{
				this._occurredAt = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.eventId;
			case 1: return this.accountId;
			case 2: return this.occurredAt;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.eventId = (System.String)fieldValue; break;
			case 1: this.accountId = (System.String)fieldValue; break;
			case 2: this.occurredAt = (System.DateTime)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
