// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.1+9110c693767c1dde2665b2b57939333478b12036
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DotNet.Kafka.MultiEventTopic
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.1+9110c693767c1dde2665b2b57939333478b12036")]
	public partial class BankAccountEvent : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""BankAccountEvent"",""namespace"":""DotNet.Kafka.MultiEventTopic"",""fields"":[{""name"":""accountId"",""type"":""string""},{""name"":""operation"",""type"":[{""type"":""record"",""name"":""DepositOperation"",""namespace"":""DotNet.Kafka.MultiEventTopic"",""fields"":[{""name"":""amount"",""type"":""double""},{""name"":""source"",""type"":""string""}]},{""type"":""record"",""name"":""TransferOperation"",""namespace"":""DotNet.Kafka.MultiEventTopic"",""fields"":[{""name"":""amount"",""type"":""double""},{""name"":""destinationAccountId"",""type"":""string""}]}]}]}");
		private string _accountId;
		private object _operation;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return BankAccountEvent._SCHEMA;
			}
		}
		public string accountId
		{
			get
			{
				return this._accountId;
			}
			set
			{
				this._accountId = value;
			}
		}
		public object operation
		{
			get
			{
				return this._operation;
			}
			set
			{
				this._operation = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.accountId;
			case 1: return this.operation;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.accountId = (System.String)fieldValue; break;
			case 1: this.operation = (System.Object)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
