// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.1+9110c693767c1dde2665b2b57939333478b12036
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DotNet.Kafka.MultiEventTopic
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.1+9110c693767c1dde2665b2b57939333478b12036")]
	public partial class TransferOperation : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"TransferOperation\",\"namespace\":\"DotNet.Kafka.MultiEventT" +
				"opic\",\"fields\":[{\"name\":\"amount\",\"type\":\"double\"},{\"name\":\"destinationAccountId\"" +
				",\"type\":\"string\"}]}");
		private double _amount;
		private string _destinationAccountId;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return TransferOperation._SCHEMA;
			}
		}
		public double amount
		{
			get
			{
				return this._amount;
			}
			set
			{
				this._amount = value;
			}
		}
		public string destinationAccountId
		{
			get
			{
				return this._destinationAccountId;
			}
			set
			{
				this._destinationAccountId = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.amount;
			case 1: return this.destinationAccountId;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.amount = (System.Double)fieldValue; break;
			case 1: this.destinationAccountId = (System.String)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
